#1 extract event sourcing from wallet wasabi
Bitcoin-Eagles/EagleSabi.Infrastructure pull request #3
Opened 2022-01-04 08:30 UTC by bitcoin-eagle

Closes #1

Imports unchanged EventSourcing code from WalletWasabi and implement dependency injection boilerplate

2022-01-07 16:35 UTC, nothingmuch requested changes, later dismissed
Concept ACK, code tested partial ACK, all commits build and pass tests except the last one, which needs some trivial fixes, see https://github.com/bitcoin-eagle/EagleSabi.Infrastructure/pull/1rr

I will open a PR for github workflow & coverage as in the other repo, maybe better to merge that first so that it affects the merge of this one?

2022-01-12 10:24 UTC, bitcoin-eagle commented
yeah, you can do the github workflow first

2022-01-12 10:29 UTC, nothingmuch commented
> yeah, you can do the github workflow first

so uh, there's a circular dependency there, because `dotnet restore` of course fails before there's any C# ;-)

opened a draft #6

2022-01-12 11:18 UTC, nothingmuch approved these changes

2022-01-12 11:19 UTC, merged